import problems
import filecmp

problems.prob_DNA()
assert filecmp.cmp("answer.txt", "sample_answers/DNA.txt")
problems.prob_RNA()
assert filecmp.cmp("answer.txt", "sample_answers/RNA.txt")
problems.prob_REVC()
assert filecmp.cmp("answer.txt", "sample_answers/REVC.txt")
problems.prob_FIB()
assert filecmp.cmp("answer.txt", "sample_answers/FIB.txt")
problems.prob_GC()
assert filecmp.cmp("answer.txt", "sample_answers/GC.txt")
problems.prob_HAMM()
assert filecmp.cmp("answer.txt", "sample_answers/HAMM.txt")
problems.prob_IPRB()
assert filecmp.cmp("answer.txt", "sample_answers/IPRB.txt")
problems.prob_PROT()
assert filecmp.cmp("answer.txt", "sample_answers/PROT.txt")
problems.prob_SUBS()
assert filecmp.cmp("answer.txt", "sample_answers/SUBS.txt")
problems.prob_CONS()
assert filecmp.cmp("answer.txt", "sample_answers/CONS.txt")
problems.prob_FIBD()
assert filecmp.cmp("answer.txt", "sample_answers/FIBD.txt")
problems.prob_GRPH()
assert filecmp.cmp("answer.txt", "sample_answers/GRPH.txt")
problems.prob_IEV()
assert filecmp.cmp("answer.txt", "sample_answers/IEV.txt")
problems.prob_LCSM()
assert filecmp.cmp("answer.txt", "sample_answers/LCSM.txt")
problems.prob_LIA()
assert filecmp.cmp("answer.txt", "sample_answers/LIA.txt")
problems.prob_MPRT()
assert filecmp.cmp("answer.txt", "sample_answers/MPRT.txt")
problems.prob_MRNA()
assert filecmp.cmp("answer.txt", "sample_answers/MRNA.txt")
problems.prob_ORF()
assert filecmp.cmp("answer.txt", "sample_answers/ORF.txt")
problems.prob_PERM()
assert filecmp.cmp("answer.txt", "sample_answers/PERM.txt")
problems.prob_PRTM()
assert filecmp.cmp("answer.txt", "sample_answers/PRTM.txt")
problems.prob_REVP()
assert filecmp.cmp("answer.txt", "sample_answers/REVP.txt")
problems.prob_SPLC()
assert filecmp.cmp("answer.txt", "sample_answers/SPLC.txt")
problems.prob_LEXF()
assert filecmp.cmp("answer.txt", "sample_answers/LEXF.txt")
problems.prob_LGIS()
assert filecmp.cmp("answer.txt", "sample_answers/LGIS.txt")
problems.prob_LONG()
assert filecmp.cmp("answer.txt", "sample_answers/LONG.txt")
problems.prob_PMCH()
assert filecmp.cmp("answer.txt", "sample_answers/PMCH.txt")
problems.prob_PPER()
assert filecmp.cmp("answer.txt", "sample_answers/PPER.txt")
problems.prob_PROB()
assert filecmp.cmp("answer.txt", "sample_answers/PROB.txt")
problems.prob_SIGN()
assert filecmp.cmp("answer.txt", "sample_answers/SIGN.txt")
problems.prob_SSEQ()
assert filecmp.cmp("answer.txt", "sample_answers/SSEQ.txt")
problems.prob_TRAN()
assert filecmp.cmp("answer.txt", "sample_answers/TRAN.txt")
problems.prob_TREE()
assert filecmp.cmp("answer.txt", "sample_answers/TREE.txt")

print "tests pass"